name: patch and deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches: [main]
  schedule:
    - cron: '52 18 * * 2'

concurrency:
  group: "deploy"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1) your repo (with custom/)
      - name: Checkout custom files
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      # 2) the official scratch‑gui
      - name: Checkout scratch-gui upstream
        uses: actions/checkout@v4
        with:
          repository: TurboWarp/scratch-gui
          path: scratch-gui
          persist-credentials: false

      # 3) pre‑build patch: copy icons & run injection script
      - name: Pre‑build patch
        run: |
          # overwrite the default project icon
          cp custom/site_icon.png \
             scratch-gui/src/lib/default-project/dango-cat.svg

          # if you still want to keep your old dango‑cat override:
          cp custom/dango-cat.svg \
             scratch-gui/src/lib/default-project/dango-cat.svg

          # now inject cursors & CSS‑var into your templates
          python3 prebuild_patch.py

      # 4) build & deploy
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v1

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Build scratch-gui
        run: |
          cd scratch-gui
          npm ci
          NODE_ENV=production ROUTING_STYLE=hash npm run build

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./scratch-gui/build/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e
